name: 'Check PR Labels'
description: 'Check if PR has required labels for deployment'

inputs:
  pr_number:
    description: 'The pull request number'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

outputs:
  environments:
    description: 'JSON string array of environments to deploy'

runs:
  using: 'composite'
  steps:
    - name: Get PR labels from GitHub API
      shell: bash
      id: pr_labels
      run: |
        PR_NUMBER="${{ inputs.pr_number }}"
        GITHUB_TOKEN="${{ inputs.github_token }}"

        PR_LABELS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels")

        # Construir array JSON con jq
        ENVIRONMENTS=$(echo '[]' | jq -c '
          . += if $labels | tostring | contains("Avalon") then ["production-avalon"] else [] end |
          . += if $labels | tostring | contains("Zircon") then ["production-zircon"] else [] end
        ' --arg labels "$PR_LABELS")

        # Establecer output con formato JSON
        echo "environments=$ENVIRONMENTS" >> $GITHUB_OUTPUT