name: 'Check PR Labels'
description: 'Check if PR has required labels for deployment'

inputs:
  pr_number:
    description: 'The pull request number'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

outputs:
  environments:
    description: 'JSON string array of environments to deploy'

runs:
  using: 'composite'
  steps:
    - name: Get PR labels from GitHub API
      shell: bash
      id: pr_labels
      run: |
        PR_NUMBER="${{ inputs.pr_number }}"
        GITHUB_TOKEN="${{ inputs.github_token }}"

        PR_LABELS=$(curl -s \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels")

        echo "DEBUG: Labels JSON => $PR_LABELS"
        echo "DEBUG: PR_NUMBER = $PR_NUMBER"

        ENVIRONMENTS="[]"
        
        if echo "$PR_LABELS" | grep -q '"name": "Avalon"'; then
          ENVIRONMENTS=$(echo "$ENVIRONMENTS" | jq '. += ["production-avalon"]')
        fi

        if echo "$PR_LABELS" | grep -q '"name": "Zircon"'; then
          ENVIRONMENTS=$(echo "$ENVIRONMENTS" | jq '. += ["production-zircon"]')
        fi

        if [[ "$ENVIRONMENTS" == "[]" ]]; then
          echo "⚠️ No valid label found. Skipping deployment."
        else
          echo "Environments to deploy: $ENVIRONMENTS"
        fi

        ENVIRONMENTS_ESCAPED=$(echo "$ENVIRONMENTS" | jq -c .)
        echo "environments=$ENVIRONMENTS_ESCAPED" >> $GITHUB_OUTPUT
        
        echo "DEBUG: Setting environments output to: $ENVIRONMENTS_ESCAPED"