name: Notify Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  notify-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify frontend team
        run: echo "Changes detected in frontend. Notify frontend team via email."