# For ussage with reusable workflows

name: Notify Backend

on:
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  notify:
    uses: ./.github/workflows/notify-team.yml
    with:
      message: "Changes detected on backend"

  print:
    runs-on: ubuntu-latest
    needs: notify
    steps:
      - run: echo "Confirmation ${{ needs.notify.outputs.confirmation }}"
