name: Deploy to Production on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR Labels
        id: check_labels
        uses: ./.github/actions/check-labels-action
        with:
          pr_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up environments for matrix
        id: setup_matrix
        run: |
          # Si environments es vacío o [], usar string vacío para evitar error de matriz vacía
          if [[ "${{ steps.check_labels.outputs.environments }}" == "[]" || "${{ steps.check_labels.outputs.environments }}" == "" ]]; then
            echo "No environments to deploy"
            echo "matrix_json={\"include\":[]}" >> $GITHUB_OUTPUT
          else
            # Construir JSON para matriz
            MATRIX=$(echo "${{ steps.check_labels.outputs.environments }}" | jq -c '{include: [.[] | {environment: .}]}')
            echo "matrix_json=$MATRIX" >> $GITHUB_OUTPUT
          fi
      
      - name: Show environments to deploy
        if: steps.setup_matrix.outputs.matrix_json != '{"include":[]}'
        run: |
          echo "Environments to deploy: ${{ steps.check_labels.outputs.environments }}"
          echo "Matrix: ${{ steps.setup_matrix.outputs.matrix_json }}"
      
  deploy:
    needs: deploy-if-merged
    if: needs.deploy-if-merged.outputs.matrix_json != '{"include":[]}' && needs.deploy-if-merged.outputs.matrix_json != ''
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.deploy-if-merged.outputs.matrix_json) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to ${{ matrix.environment }}
        uses: ./.github/workflows/deploy-environment
        with:
          environment: ${{ matrix.environment }}