name: Deploy to Production on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.check_labels.outputs.environments }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR Labels
        id: check_labels
        uses: ./.github/actions/check-labels-action
        with:
          pr_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Debug environments output
        run: |
          echo "Environments output value: '${{ steps.check_labels.outputs.environments }}'"
          echo "Is empty: '${{ steps.check_labels.outputs.environments == '' }}'"
          echo "Is []?: '${{ steps.check_labels.outputs.environments == '[]' }}'"
  
  # Job para desplegar a Avalon si se detecta esa etiqueta
  deploy-avalon:
    needs: deploy-if-merged
    if: contains(needs.deploy-if-merged.outputs.environments, 'production-avalon')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Production Avalon
        uses: ./.github/workflows/deploy-environment
        with:
          environment: production-avalon
  
  # Job para desplegar a Zircon si se detecta esa etiqueta
  deploy-zircon:
    needs: deploy-if-merged
    if: contains(needs.deploy-if-merged.outputs.environments, 'production-zircon')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Production Zircon
        uses: ./.github/workflows/deploy-environment
        with:
          environment: production-zircon